"""Generated Arabic traceback localization data."""

# Generated from lexicon/messages.toml. Do not edit by hand.
# fmt: off
# ruff: noqa: E501

import re

EXCEPTION_NAMES_AR: dict[str, str] = {
    'BaseException': 'استثناء_أساسي',
    'Exception': 'استثناء_عام',
    'GeneratorExit': 'خروج_مولد',
    'KeyboardInterrupt': 'مقاطعة',
    'SystemExit': 'خروج_نظام',
    'ArithmeticError': 'خطأ_حسابي',
    'FloatingPointError': 'خطأ_عشري',
    'OverflowError': 'خطأ_فائض',
    'ZeroDivisionError': 'خطأ_قسمة_صفر',
    'AssertionError': 'خطأ_تأكيد',
    'AttributeError': 'خطأ_صفة',
    'NameError': 'خطأ_اسم',
    'UnboundLocalError': 'خطأ_متغير_غير_مرتبط',
    'BufferError': 'خطأ_مخزن_مؤقت',
    'EOFError': 'خطأ_نهاية_ملف',
    'ImportError': 'خطأ_استيراد',
    'ModuleNotFoundError': 'خطأ_وحدة_مفقودة',
    'LookupError': 'خطأ_بحث',
    'IndexError': 'خطأ_فهرس',
    'KeyError': 'خطأ_مفتاح',
    'MemoryError': 'خطأ_ذاكرة',
    'OSError': 'خطأ_نظام',
    'EnvironmentError': 'خطأ_بيئه',
    'IOError': 'خطأ_إدخال_إخراج',
    'BlockingIOError': 'خطأ_إدخال_إخراج_حاجب',
    'ChildProcessError': 'خطأ_عمليه_فرعيه',
    'ConnectionError': 'خطأ_اتصال',
    'BrokenPipeError': 'خطأ_انبوب_مكسور',
    'ConnectionAbortedError': 'خطأ_اتصال_ملغي',
    'ConnectionRefusedError': 'خطأ_اتصال_مرفوض',
    'ConnectionResetError': 'خطأ_اتصال_منقطع',
    'FileExistsError': 'خطأ_ملف_موجود',
    'FileNotFoundError': 'خطأ_ملف_مفقود',
    'InterruptedError': 'خطأ_مقاطعه',
    'IsADirectoryError': 'خطأ_هذا_مجلد',
    'NotADirectoryError': 'خطأ_ليس_مجلدا',
    'PermissionError': 'خطأ_صلاحية',
    'ProcessLookupError': 'خطأ_بحث_عمليه',
    'TimeoutError': 'خطأ_انتهاء_وقت',
    'ReferenceError': 'خطأ_مرجع',
    'RuntimeError': 'خطأ_تشغيل',
    'NotImplementedError': 'خطأ_غير_منفذ',
    'RecursionError': 'خطأ_عودية',
    'SystemError': 'خطأ_نظام_داخلي',
    'StopIteration': 'انتهاء_التكرار',
    'StopAsyncIteration': 'ايقاف_التكرار_المتزامن',
    'SyntaxError': 'خطأ_صياغة',
    'IndentationError': 'خطأ_إزاحة',
    'TabError': 'خطأ_جدولة',
    'TypeError': 'خطأ_نوع',
    'UnicodeError': 'خطأ_يونيكود',
    'UnicodeDecodeError': 'خطأ_فك_يونيكود',
    'UnicodeEncodeError': 'خطأ_ترميز_يونيكود',
    'UnicodeTranslateError': 'خطأ_ترجمه_يونيكود',
    'ValueError': 'خطأ_قيمة',
    'Warning': 'تحذير',
    'BytesWarning': 'تحذير_بايت',
    'DeprecationWarning': 'تحذير_اهمال',
    'EncodingWarning': 'تحذير_ترميز',
    'FutureWarning': 'تحذير_مستقبلي',
    'ImportWarning': 'تحذير_استيراد',
    'PendingDeprecationWarning': 'تحذير_اهمال_قادم',
    'ResourceWarning': 'تحذير_موارد',
    'RuntimeWarning': 'تحذير_تشغيل',
    'SyntaxWarning': 'تحذير_صياغه',
    'UnicodeWarning': 'تحذير_يونيكود',
    'UserWarning': 'تحذير_مستخدم',
    'BaseExceptionGroup': 'مجموعه_استثنائات_اساسيه',
    'ExceptionGroup': 'مجموعه_استثنائات',
}

_MSG_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile('^division by zero$'), 'القسمة على صفر'),
    (re.compile('^integer division or modulo by zero$'), 'قسمة صحيحة أو باقي على صفر'),
    (re.compile('^float division by zero$'), 'قسمة عشرية على صفر'),
    (re.compile('^float modulo$'), 'باقي قسمة عشرية على صفر'),
    (re.compile('^complex division by zero$'), 'قسمة عدد مركب على صفر'),
    (re.compile("^name '(?P<name>[^']+)' is not defined$"), "الاسم '{name}' غير معرّف"),
    (re.compile("^name '(?P<name>[^']+)' is not defined\\. Did you mean: '(?P<sugg>[^']+)'\\?$"), "الاسم '{name}' غير معرّف. هل تقصد: '{sugg}'؟"),
    (re.compile("^free variable '(?P<name>[^']+)' referenced before assignment in enclosing scope$"), "المتغير الحر '{name}' مستخدم قبل تعريفه في النطاق المحيط"),
    (re.compile("^local variable '(?P<name>[^']+)' referenced before assignment$"), "المتغير المحلي '{name}' مستخدم قبل تعريفه"),
    (re.compile("^'(?P<type>[^']+)' object has no attribute '(?P<attr>[^']+)'$"), "الكائن من نوع '{type}' لا يملك الخاصية '{attr}'"),
    (re.compile("^'(?P<type>[^']+)' object is not subscriptable$"), "الكائن من نوع '{type}' لا يقبل الفهرسة"),
    (re.compile("^'(?P<type>[^']+)' object is not callable$"), "الكائن من نوع '{type}' غير قابل للاستدعاء"),
    (re.compile("^'(?P<type>[^']+)' object is not iterable$"), "الكائن من نوع '{type}' غير قابل للتكرار"),
    (re.compile("^'(?P<type>[^']+)' object cannot be interpreted as an integer$"), "الكائن من نوع '{type}' لا يمكن تفسيره كعدد صحيح"),
    (re.compile("^argument of type '(?P<type>[^']+)' is not iterable$"), "الوسيط من نوع '{type}' غير قابل للتكرار"),
    (re.compile('^list index out of range$'), 'فهرس القائمة خارج النطاق'),
    (re.compile('^tuple index out of range$'), 'فهرس الصف خارج النطاق'),
    (re.compile('^string index out of range$'), 'فهرس النص خارج النطاق'),
    (re.compile('^bytearray index out of range$'), 'فهرس مصفوفة البايت خارج النطاق'),
    (re.compile('^range object index out of range$'), 'فهرس كائن النطاق خارج النطاق'),
    (re.compile('^pop index out of range$'), 'فهرس الإخراج خارج النطاق'),
    (re.compile('^pop from empty list$'), 'إخراج من قائمة فارغة'),
    (re.compile('^pop from an empty (set|deque|dict)$'), 'إخراج من {1} فارغ'),
    (re.compile('^maximum recursion depth exceeded(?P<rest>.*)$'), 'تم تجاوز عمق العودية الأقصى{rest}'),
    (re.compile("^No module named '(?P<name>[^']+)'$"), "لا توجد وحدة باسم '{name}'"),
    (re.compile("^cannot import name '(?P<name>[^']+)' from partially initialized module '(?P<module>[^']+)'(?P<rest>.*)$"), "لا يمكن استيراد الاسم '{name}' من الوحدة المُهيَّأة جزئياً '{module}' (على الأرجح بسبب استيراد دائري)"),
    (re.compile("^cannot import name '(?P<name>[^']+)' from '(?P<module>[^']+)'(?P<rest>.*)$"), "لا يمكن استيراد الاسم '{name}' من '{module}'{rest}"),
    (re.compile('^attempted relative import with no known parent package$'), 'محاولة استيراد نسبي دون وجود حزمة أصلية معروفة'),
    (re.compile("^unsupported operand type\\(s\\) for (?P<op>\\S+): '(?P<a>[^']+)' and '(?P<b>[^']+)'$"), "أنواع المعاملات غير مدعومة لـ {op}: '{a}' و '{b}'"),
    (re.compile('^can only concatenate (?P<a>\\w+) \\(not \\"(?P<b>\\w+)\\"\\) to \\w+$'), 'يمكن فقط ضم {a} (لا {b}) إلى {a}'),
    (re.compile("^invalid literal for int\\(\\) with base (?P<base>\\d+): '(?P<val>[^']*)'$"), "قيمة غير صالحة للدالة int() بالأساس {base}: '{val}'"),
    (re.compile("^could not convert string to float: '(?P<val>[^']*)'$"), "تعذر تحويل النص إلى عدد عشري: '{val}'"),
    (re.compile('^expected (?P<n>\\d+) (?P<arg_kind>positional argument|positional arguments), got (?P<got>\\d+)$'), 'كان متوقعا {n} {arg_kind} لكن تم تمرير {got}'),
    (re.compile('^(?P<func>[^(]+)\\(\\) missing (?P<n>\\d+) required positional argument(?P<plural>s?): (?P<rest>.+)$'), '{func}() ينقصها {n} وسيط إجباري{plural}: {rest}'),
    (re.compile("^(?P<func>[^(]+)\\(\\) got an unexpected keyword argument '(?P<name>[^']+)'$"), "{func}() استلمت وسيطا مفتاحيا غير متوقع '{name}'"),
    (re.compile("^\\[Errno (?P<errno>\\d+)\\] (?P<msg>[^:]+): '(?P<path>.+)'$"), "[رقم الخطأ {errno}] {msg}: '{path}'"),
    (re.compile('^\\[Errno (?P<errno>\\d+)\\] (?P<msg>.+)$'), '[رقم الخطأ {errno}] {msg}'),
    (re.compile('^\\[WinError (?P<errno>\\d+)\\] (?P<msg>.+)$'), '[خطأ ويندوز {errno}] {msg}'),
    (re.compile('^list indices must be integers or slices, not (?P<type>\\w+)$'), "فهارس القائمة يجب أن تكون أعداداً صحيحة أو شرائح، لا '{type}'"),
    (re.compile('^tuple indices must be integers or slices, not (?P<type>\\w+)$'), "فهارس الصف يجب أن تكون أعداداً صحيحة أو شرائح، لا '{type}'"),
    (re.compile("^string indices must be integers(?:, not '(?P<type>[^']+)')?$"), 'فهارس النص يجب أن تكون أعداداً صحيحة'),
    (re.compile("^object of type '(?P<type>[^']+)' has no len\\(\\)$"), "الكائن من نوع '{type}' لا يملك دالة len()"),
    (re.compile("^unhashable type: '(?P<type>[^']+)'$"), "النوع '{type}' غير قابل للتجزئة"),
    (re.compile("^'(?P<type>[^']+)' object is not an iterator$"), "الكائن من نوع '{type}' ليس مكرراً"),
    (re.compile("^a bytes-like object is required, not '(?P<type>[^']+)'$"), "مطلوب كائن من نوع bytes، لا '{type}'"),
    (re.compile('^(?P<func>[^(]+)\\(\\) takes (?P<n>\\d+) positional argument(?P<plural>s?) but (?P<got>\\d+) (?:were|was) given$'), '{func}() تأخذ {n} وسيط موضعي{plural} لكن تم تمرير {got}'),
    (re.compile('^sequence item (?P<n>\\d+): expected str instance, (?P<got>\\w+) found$'), 'عنصر المتسلسلة {n}: متوقع نص، وجد {got}'),
    (re.compile("^(?P<func>[^(]+)\\(\\) got multiple values for argument '(?P<name>[^']+)'$"), "{func}() استلمت قيماً متعددة للوسيط '{name}'"),
    (re.compile("^bad operand type for unary (?P<op>[^:]+): '(?P<type>[^']+)'$"), "نوع معامل خاطئ للعملية الأحادية {op}: '{type}'"),
    (re.compile("^'(?P<type>[^']+)' object does not support item assignment$"), "الكائن من نوع '{type}' لا يدعم تعيين العناصر"),
    (re.compile("^'(?P<type>[^']+)' object doesn't support item (?P<op>assignment|deletion)$"), "الكائن من نوع '{type}' لا يدعم {op} العناصر"),
    (re.compile("^can't multiply sequence by non-int of type '(?P<type>[^']+)'$"), "لا يمكن ضرب المتسلسلة بنوع غير صحيح '{type}'"),
    (re.compile('^expected str, bytes or os\\.PathLike object, not (?P<type>\\w+)$'), "متوقع نص أو بايتات أو مسار، ليس '{type}'"),
    (re.compile("^descriptor '(?P<desc>[^']+)' for '(?P<for_type>[^']+)' objects doesn't apply to a '(?P<got_type>[^']+)' object$"), "الواصف '{desc}' لكائنات '{for_type}' لا ينطبق على كائن '{got_type}'"),
    (re.compile("^cannot access local variable '(?P<name>[^']+)' where it is not associated with a value$"), "لا يمكن الوصول إلى المتغير المحلي '{name}' لأنه غير مرتبط بقيمة"),
    (re.compile("^'(?P<type>[^']+)' object has no attribute '(?P<attr>[^']+)'\\. Did you mean: '(?P<sugg>[^']+)'\\?$"), "الكائن من نوع '{type}' لا يملك الخاصية '{attr}'. هل تقصد: '{sugg}'؟"),
    (re.compile("^module '(?P<module>[^']+)' has no attribute '(?P<attr>[^']+)'$"), "الوحدة '{module}' لا تملك الخاصية '{attr}'"),
    (re.compile("^module '(?P<module>[^']+)' has no attribute '(?P<attr>[^']+)'\\. Did you mean: '(?P<sugg>[^']+)'\\?$"), "الوحدة '{module}' لا تملك الخاصية '{attr}'. هل تقصد: '{sugg}'؟"),
    (re.compile('^too many values to unpack \\(expected (?P<n>\\d+)\\)$'), 'قيم كثيرة جداً للتفريغ (متوقع {n})'),
    (re.compile('^not enough values to unpack \\(expected (?P<n>\\d+), got (?P<got>\\d+)\\)$'), 'قيم غير كافية للتفريغ (متوقع {n}، حصلنا على {got})'),
    (re.compile('^math domain error$'), 'خطأ في نطاق الرياضيات'),
    (re.compile('^substring not found$'), 'النص الفرعي غير موجود'),
    (re.compile('^list\\.remove\\(x\\): x not found$'), 'list.remove(x): العنصر غير موجود في القائمة'),
    (re.compile('^I/O operation on closed file\\.$'), 'عملية إدخال/إخراج على ملف مغلق'),
    (re.compile('^Circular reference detected$'), 'تم اكتشاف مرجع دائري'),
    (re.compile('^empty separator$'), 'الفاصل فارغ'),
    (re.compile('^dictionary update sequence element #(?P<n>\\d+) has length (?P<got>\\d+); 2 is required$'), 'عنصر تسلسل تحديث القاموس رقم {n} له طول {got}؛ المطلوب 2'),
    (re.compile('^math range error$'), 'خطأ في مجال الرياضيات'),
    (re.compile('^int too large to convert to float$'), 'العدد الصحيح كبير جداً للتحويل إلى عشري'),
    (re.compile("^\\(\\d+, '(?P<msg>[^']+)'\\)$"), 'خطأ عملية: {msg}'),
    (re.compile('^generator already executing$'), 'المولّد قيد التنفيذ بالفعل'),
    (re.compile('^coroutine already executing$'), 'الكوروتين قيد التنفيذ بالفعل'),
    (re.compile('^dictionary changed size during iteration$'), 'تغيّر حجم القاموس أثناء التكرار'),
    (re.compile('^[Ss]et changed size during iteration$'), 'تغيّر حجم المجموعة أثناء التكرار'),
    (re.compile('^asynchronous generator raised StopIteration$'), 'المولّد غير المتزامن أطلق ايقاف_التكرار'),
    (re.compile('^invalid syntax$'), 'صياغة غير صالحة'),
    (re.compile('^invalid syntax\\. Perhaps you forgot a comma\\?$'), 'صياغة غير صالحة. ربما نسيت فاصلة؟'),
    (re.compile('^unterminated string literal \\(detected at line (?P<line>\\d+)\\)$'), 'نص حرفي غير منتهٍ (اكتُشف في السطر {line})'),
    (re.compile('^EOL while scanning string literal$'), 'نهاية السطر أثناء فحص نص حرفي'),
    (re.compile('^unexpected EOF while parsing$'), 'نهاية ملف غير متوقعة أثناء التحليل'),
    (re.compile('^unexpected character after line continuation character$'), 'حرف غير متوقع بعد حرف استمرار السطر'),
    (re.compile("^invalid character '(?P<char>[^']+)' \\((?P<code>U\\+[0-9A-Fa-f]+)\\)$"), "حرف غير صالح '{char}' ({code})"),
    (re.compile("^Missing parentheses in call to '(?P<func>[^']+)'\\. Did you mean (?P<sugg>.+)\\?$"), "أقواس مفقودة في استدعاء '{func}'. هل تقصد {sugg}؟"),
    (re.compile('^f-string expression part cannot include a backslash$'), 'جزء تعبير النص المنسق لا يمكن أن يحتوي على شرطة مائلة عكسية'),
    (re.compile('^expected an indented block(?P<rest>.*)$'), 'متوقع كتلة مزاحة{rest}'),
    (re.compile('^inconsistent use of tabs and spaces in indentation$'), 'استخدام غير متسق للجداول والمسافات في الإزاحة'),
    (re.compile('^unindent does not match any outer indentation level$'), 'الإزاحة لا تطابق أي مستوى خارجي'),
    (re.compile('^coroutine raised StopIteration$'), 'الكوروتين أطلق ايقاف_التكرار'),
    (re.compile('^Connection refused$'), 'رُفض الاتصال'),
    (re.compile('^Connection timed out$'), 'انتهت مهلة الاتصال'),
    (re.compile('^timed out$'), 'انتهت المهلة'),
    (re.compile('^Connection reset by peer$'), 'أعاد الطرف الآخر ضبط الاتصال'),
    (re.compile('^Broken pipe$'), 'الأنبوب معطوب'),
    (re.compile("^'(?P<codec>[^']+)' codec can't decode byte (?P<byte>0x[0-9a-f]+) in position (?P<pos>\\d+): (?P<reason>.+)$"), "ترميز '{codec}' لا يستطيع فك تشفير البايت {byte} في الموضع {pos}: {reason}"),
    (re.compile("^'(?P<codec>[^']+)' codec can't decode bytes? in position (?P<start>\\d+)-(?P<end>\\d+): (?P<reason>.+)$"), "ترميز '{codec}' لا يستطيع فك تشفير البايتات في الموضع {start}-{end}: {reason}"),
    (re.compile("^'(?P<codec>[^']+)' codec can't encode character '(?P<char>[^']+)' in position (?P<pos>\\d+): (?P<reason>.+)$"), "ترميز '{codec}' لا يستطيع ترميز الحرف '{char}' في الموضع {pos}: {reason}"),
    (re.compile("^'(?P<codec>[^']+)' codec can't encode characters? in position (?P<start>\\d+)-(?P<end>\\d+): (?P<reason>.+)$"), "ترميز '{codec}' لا يستطيع ترميز الأحرف في الموضع {start}-{end}: {reason}"),
    (re.compile("^'(?P<key>[^']+)'$"), "المفتاح '{key}' غير موجود"),
]

MESSAGE_TEMPLATES_AR = _MSG_PATTERNS
